export type KaliChapter = {
  numeral: string;
  title: string;
  subtitle: string;
  body: string[];
};

export const KALI_CHAPTERS: KaliChapter[] = [
  {
    "numeral": "I",
    "title": "The Village",
    "subtitle": "The fall of Dharika",
    "body": [
      "Set 1880’s, A little distance from Palakkad is the village of Chittur. In the evening, as the sky darkened, the paddy fields shimmered like gold in the fading sunlight. After the rain, a cool breeze swept gently through the central courtyard of Karimana Illam. The old mansion’s walls stood in the dim light, their shadows echoing on the faces of those inside. In the prayer room, a lamp burned steadily. Parameswaran Namboothiri, eyes closed, chanted mantras in the light of the lamp. The scent of roasted rice and the coolness of tulsi leaves filled the prayer room. Ambika Antharjanam stepped out from inside, dressed in a black blouse and white sari with a black border. She swept the corners of the house with a broom, then cleaned the front yard. Afterward, she called out to Parvathi: “Mole, evening is falling, light the lamps.”",
      "Parvathi emerged from her room, her dusky skin and long hair flowing. She wore a black blouse and a white sari with a black border. Holding a lamp, she walked to the prayer room. In the fading evening light, her clothes glowed softly; a thin gold chain around her neck and small studs sparkled in her ears. Tulsi leaves adorned her hair, and golden chains on her ankles gleamed. Lighting the lamp, she walked to the front of the house, its glow shining as a beacon of hope. Her footsteps glided soundlessly across the stone floor; dragonflies flitted in the evening breeze. “Amme,” Parvathi called gently. “Shall I fetch water for Achhan?” Ambika replied, “Yes, mole. Bring it after his prayers.” Parvathi quietly walked to the kitchen.",
      "As evening settled in, after prayers, the nearby Nair farmer Mahadevan and his son Neelakandan arrived at Karimana Illam—faces darkened by the setting sun, sweat glistening. Both wore simple full-sleeve shirts and white mundus with black borders; their hair was long and slightly wavy, their skin dusky. Parameswaran welcomed them politely. “Namaskaram, Namboothiri-etta,” Mahadevan said respectfully. Parameswaran smiled, “Come in, the evening is cool. Parvathi, bring water for our guests.” Parvathi brought water in two copper vessels, passing them gently. Neelakandan watched her closely. Parvathi kept her eyes down, handing over the water, then retreated to lean against the wall behind her father. “Thank you, mole,” Mahadevan and Neelakandan said, drinking the water.",
      "“We need a few banana saplings for a patch in the field,” Mahadevan explained. Parameswaran nodded, “Take as many as you need. May your fields prosper.” Neelakandan, in a quiet voice, said, “Your kindness is known across the village, Namboothiri-etta. Thank you. ” Ambika, leaning quietly against a portion of the wall, bowed her head downward and listened as the men spoke. Neelakandan kept glancing at Parvathi, who stood near the lamp, eyes lowered. When their gazes met, Parvathi smiled shyly at Neelakandan. After some conversation, Mahadevan and Neelakandan left as the deepening evening wrapped the house in darkness."
    ]
  },
  {
    "numeral": "II",
    "title": "The Festival",
    "subtitle": "A prayer beneath the drums",
    "body": [
      "Long ago, in the realm of gods and demons, the demon king Dharika spread chaos everywhere. He had a unique boon—only a woman could kill him, not a man. His loud voice made the mountains tremble. The gods, in fear and worry, sought Badrakali’s help. In heaven, Badrakali stood radiant, wild hair flowing, her dark body and blazing eyes fierce. “If the world must be saved, I will do it,” she declared bravely, raising her sword. Her powerful voice echoed in the sky, as black clouds and lightning gathered around her. The gods watched in awe, hoping Badrakali would restore peace. Back in the village, years passed. The house’s roof grew weaker, the fields harder to cultivate. By the paddy fields, villagers built a new Badrakali temple from black stone. Every year, a festival drew people from all directions. On festival day, the drums thundered.",
      "Villagers gathered in the temple courtyard, faces aglow in the light of burning torches. Parvathi wore a red sari with a golden border, her hair adorned with jasmine. She offered tulsi leaves and red hibiscus on a copper plate to the goddess, bowing with folded hands. Standing with her parents, she was filled with excitement and a little anxiety. The air was fragrant with flowers and incense. Neelakandan, in a black full-sleeve shirt and white mundu with a black border, prayed to Kali and approached Parvathi. The priest gave them offerings—banana leaves, sandalwood, and hibiscus petals. Amidst the crowd, Neelakandan searched for her. Their eyes met. Parvathi tucked her wind-blown hair behind her ear with her fingers. Neelakandan smiled back, his heart racing. He longed to speak to her, but words failed him.",
      "Ambika noticed and whispered to her husband, “See how that Nair boy looks at our mole?” Parameswaran ignored it, eyes on the crowd. “Not now, Ambika. This isn’t the time.” On stage, actors performed the legend of Badrakali and Dharika: their confcrontation, the wild-eyed actress playing Badrakali, her hair loose and fierce gaze. As Dharika fell to the ground, she raised her sword and cried, “For justice For the world” The crowd erupted in applause, their voices rising above the drums. Neelakandan moved closer to Kali’s idol, whispering a prayer: “Kali Amma, may I have the fortune to live with her, may she be my bride.” Elsewhere, Parameswaran’s distant relative Bhairavan Namboothiri surveyed his land. He longed to be a great landlord, gathering more property.",
      "Tall, thin, with long hair and a perpetually suspicious face, Bhairavan wore expensive garments and gold spectacles for pride. His wife Bhavani appeared gentle but was cold and cunning within. Their daughter, Gauri, sat on the steps, dreaming of marrying Neelakandan one day, dressed in beautiful clothes and jewelry. Bhairavan spoke quietly, “Bhavani, we must secure our future. Somehow, Parameswaran’s land must become ours.” Bhavani smiled, “With kindness and trickery, we’ll get what we want.” Gauri smiled, adorning her hair with a hibiscus flower. “Can I be the bride, Amma?” Bhavani lovingly touched her forehead, “Fate will favor us, mole. I believe your wish will come true one day.” In Bhairavan’s family history, his brother Chandrapaal was married to Bhargavi; using his dark magic, Bhairavan sowed discord between them.",
      "Another brother, Somesh, and his wife Subhadra also suffered due to Bhairavan’s sorcery—even her pregnancy ended in tragedy. With no heirs, their lands and property came under his control."
    ]
  },
  {
    "numeral": "III",
    "title": "Gathering Darkness",
    "subtitle": "Love, land and old divisions",
    "body": [
      "On a stormy, rain-soaked night, disaster struck Neelakandan’s home. His father, Mahadevan, was bedridden with a severe fever and illness. His mother Saraswati sat beside him, rubbing his feet and praying through tears. “Achan, hold on,” Neelakandan pleaded, gripping his father’s hand. Mahadevan looked lovingly at his son, “Take care of your mother, mone. Never let her suffer; never forget Kali Amma.” When Mahadevan passed away, Saraswati was shattered with grief. Neelakandan held her close, his own heart broken. Weeks slipped by. Saraswati stopped speaking, her eyes emptied of life. Neelakandan felt alone. Finally, Neelakandan decided to ask for Parvathi’s hand in marriage. One evening, dressed in a black full-sleeve shirt and white mundu with a black border, he arrived at Karimana Illam.",
      "Parameswaran sat in the porch, polishing a brass lamp. “Namaskaram, Namboothiri-etta,” Neelakandan said nervously. Parameswaran nodded, “You seem troubled, mone. Speak your mind.” Neelakandan folded his hands, “I wish to marry Parvathi. I know our castes are different, but my love is true. I cannot imagine a life without her. I promise to cherish her always.” Ambika, leaning quietly against a portion of the wall, was moved, her eyes filling with pain. “Neelakanda, we respect you. But we cannot break our family’s traditions and honor,” she said. Parameswaran sighed, “You are like a son to me, but this cannot be.” Neelakandan bowed his head, “If that is your wish, I will not trouble you again.” Parvathi, listening in the shadows, struggled to hold back tears. Bhairavan saw his chance.",
      "With Bhavani and Gauri, he visited Saraswati at the Badrakali temple festival, bringing sweets and speaking kindly. “Poor chechi,” Bhavani said gently. “You have only one son. If our families unite, life will be easier. Gauri is like your daughter, isn’t she?” Saraswati nodded weakly, “Neelakandan is all I have. I just want him to be happy.” Gauri smiled at Neelakandan, “Ettah, will you take me to the Kali temple festival?” she asked sweetly. Neelakandan tried to smile, but his mind was elsewhere. Bhairavan plotted further. He spoke quietly to his son Ishaan, “Now you must marry Parvathi. Then Parameswaran’s land will be ours.” Ishaan nodded. Bhairavan approached Neelakandan and said softly, “Parameswaran’s family looks down on us. They say we are not pure.” Neelakandan clenched his fists in anger but said nothing.",
      "Bhairavan, with a hidden meaning, said, “Let us be allies. I am getting older; I can’t manage everything alone. Remember, in this world, wealth and power matter most.”"
    ]
  },
  {
    "numeral": "IV",
    "title": "The Descent",
    "subtitle": "When the goddess answers",
    "body": [
      "As the Badrakali festival approached, Bhairavan turned to dark magic. In secret, he lit lamps, chanted mantras, and tied black threads to clay dolls. Gauri and Bhargavan helped him with these rituals. At Karimana Illam, Parameswaran and Ambika felt uneasy. “I feel a darkness over our home,” Ambika whispered, gripping her husband’s hand. Lines of worry creased Parameswaran’s face. “I feel something bad is coming. We must pray more. Kali Amma will protect us,” he reassured Ambika. Parvathi spent long hours at the temple, praying. “Kali Amma, save us from evil. Bring light back to our home. May I have the fortune to live with Neelakandan, and may my parents accept our bond.” Neelakandan, feeling that same darkness, began spending his nights alone at the Kali temple. Kneeling before the goddess, he cried, “Amma, make me strong.",
      "Let me protect those I love.” The next day, as quarrels and disagreements brewed between Bhairavan and Parameswaran, Bhairavan brought Bhavani, Ishaan, and Gauri to Parameswaran’s house. “We wish for Ishaan and Parvathi’s marriage,” Bhairavan announced. Ambika looked at Parameswaran with concern. “We are struggling financially,” Parameswaran said quietly. “We must secure our daughter’s future.” Parvathi stood helplessly, listening. One night, amid thunder and lightning, Neelakandan dreamt of Badrakali. She stood before him, powerful and strong. “Be strong, my child. There are many shadows in this world, but you are not alone,” the goddess said. Neelakandan awoke in tears. In the legend, Badrakali and Dharika met on the battlefield. Badrakali’s dark body, wild hair flying in the wind, fierce eyes, and four arms created a fearsome sight.",
      "Around her waist, she wore a chain of severed hands, and around her neck, a garland of asura heads. In her upper left hand, she held a long, half-curved sword; in her lower left, the Sudarshana wheel. In her upper right hand, she grasped a demon’s head; in her lower right, a vessel filled with blood. Dharika mocked her: “You are just a woman, you can never defeat me.” Badrakali was unafraid; she smiled, “A woman’s fury will destroy evil.” Holding her sword, she marched toward Dharika. As the battle began, sparks and blood filled the sky. The gods watched with excitement. In the Amidst dark dense, shadowy trees stands a black kaali stone temple near the Bhavani river, with Kunnampidari Hill in the background.",
      "The temple has a rectangular shape and an odu-tiled roof, with the goddess Kali’s idol made of black stone installed inside, and another rectangular black stone platform outside. For Parvathi’s wedding, the temple was decorated with white arali flowers and colorful drawings of Kali on the ground in front. As rituals peaked, the temple filled with lamps, music, and the sound of drums. Parvathi, trembling in a red sari, entered the mandapam with her parents, where Ishan, Bhairavan, Bhavani, and the temple priest stood. On seeing Neelakanthan, Parvathi ran from the mandapam, hugged him, and wept. Neelakanthan comforted her, which deeply insulted Bhairavan’s family. Angered, Ishan pulled Parvathi aside, struck her on the cheek, and she fell onto the Kali drawing before the temple.",
      "Ishan then grabbed her hair, smashed her head against the rectangular Kali stone, causing her forehead to bleed onto the idol. He threw her aside, leaving Parvathi unconscious before the Kali image. As everyone stood in shock, a furious wind swept through, scattering the ashes from the Kali drawing. At that moment, the goddess Kali’s spirit entered Parvathi. She slowly rose, Kali slowly raised her right hand, bowed her head, and with her left hand, smeared the black ash lying nearby onto her face. She shook her head from side to side, loosened her hair, and screamed loudly.",
      "Dropping to her knees before the rectangular stone, she drew a sword from the earth and circled the stone in a trance, as she raised her head and looked upward, then knelt down, bringing both hands behind her as she let out a powerful roar: “Errrrr, Hraaaa, Hreeeem, ready to confront those who had wronged her. Her voice rose sharply— “Errrr, I will not marry him” Her scream shook the whole temple; the crowd stood frozen. “Parvathi, please—” Ishaan stepped forward. Parvathi, now in Badrakali’s booming voice: “If you touch me, and you will be died” Bhairavan, angrily: “You sit here This marriage must take place” But a divine force surged from Parvathi’s body. Without fear, she took the sword from the altar and stood before Ishaan. The blade gleamed in the firelight. “Your evil ends today. You cannot control us.”",
      "The sound of the sword—sharp and fiery—resounded through the temple. She swung the sword, Errrr, hreeee a fierce scream once again. Badrakali approached Ishan and drove her sword deep into his chest. Ishan fell to his knees. In fierce rage, the goddess pressed her right foot on his shoulder and pulled the sword back out. Ishaan fell to the ground, blood flowing. The priest retreated in fear. In that moment, Badrakali had descended into Parvathi, she moved forward like wild fire, her eyes ablaze. Neelakandan rushed forward: “Parvathi It’s me—Neelakandan Listen, mole” Parvathi pushed him aside and faced Bhairavan. Bhairavan, kneeling by his son’s body, wept In his rage, Bhairavan picked up the other sword and charged at Parvathi.",
      "But Kali’s divine power rose from within her, Parvathi moved toward Bhairavan, leapt up, and swung her sword at him with force. and in an instant Bhairavan was beheaded. Standing nearby, Parvathi seized Gauri by the neck, lifted her into the air, and leaned her neck in to one portion after her life ebbed away, gently laid her on the ground. All around, people were filled with fear and awe—some stood with folded hands, others chanted “Kali Badrakali” in terror. The screams, the fiery sword, the spreading fear, and the presence of divine power turned the temple into a battlefield. Bhavani, having witnessed everything in terror, tried to move backward. But Parvathi grabbed her by the hair, pulled her back, and slammed the back of her head against the stone wall of the Kali temple. Blood flowed, and Bhavani died instantly.",
      "Errrr, Eha hahahaaaa haaaa, hreeee Parvathi screamed loudly, her voice sending tremors through the ground. The tightly packed crowd around her recoiled in fear, trembling and stunned. At last, unable to control her anger, Parvathi picked up the sword again and paced back and forth, shouting. Those gathered watched in fear and stepped away, while Neelakandan stood helplessly, unable to intervene. The next moment, Neelakandan lied to the ground, but Parvathi, not noticing this, moved forward and then turned back. As she did, she unknowingly stepped on Neelakandan’s chest. Suddenly, Parvathi became motionless. Tears streamed down her cheeks as she looked down and saw Neelakandan. Instantly, she stepped back and threw the sword far away, turned around, covered her face with her hands, and cried out loudly.",
      "Neelakandan slowly got up from the ground and moved closer to Parvathi, who then collapsed to the ground, unconscious. Ambika ran to her and embraced her. “Mole, come back. You are safe,” she whispered. Parameswaran wept, “Kali Amma, thank you.” Parvathi remembered nothing of what happened afterward. The villagers whispered, “Kali’s curse has come. Justice is done.” Parvathi, weak but safe, was taken home. Neelakandan visited her every day, sitting by her side and holding her hand. One evening, as the sun set, Parvathi asked, “When you first saw me, did you know?” Neelakandan smiled, wiping a tear from her cheek. “I knew my life had changed. You are my goddess, Parvathi.” She blushed and pressed her forehead to his. “With you, I am not afraid.”",
      "They sat quietly together, listening to the temple bells—the sound full of memories, myths, anger, love, justice, and hope."
    ]
  }
];

export const KALI_AUTHOR_NOTE = "Arjun krishna were lived in Calicut, He completed his B.A. in English through distance education at the University of Calicut, and later pursued his M.A. in English at the same university, also through distance education. His debut novel is The Immolation to Kirat, and his second work is the short story 'Kali – The Black Goddess, and he were an ardent devotee of lord shiva and goddess bhagavathi. he were pilgrim. he loves to proceeded pilgrimage to lord shiva, goddess bhagavathi temple. where he were reached the temple, he were deeply adapted to the territory of the temple, he pursued more about the temple and perceived Its the past, formally the temple and Its territory were shaped to being the apart as the story to the extent, the things were ensued at earlier were It caused to be portion of the story. he used to write short stories and poems where he were studied in college. he tries to Incorporate into the story what is going on around him. he tries to explore the extant things through his expidation.";

